!IFNDEF BUILD_DIR
BUILD_DIR=build-msvc-light
!ENDIF

!IFNDEF CONFIG
CONFIG=Release
!ENDIF

!IFNDEF GENERATOR
GENERATOR=NMake Makefiles
!ENDIF

!IFNDEF EMBREE_DIR
EMBREE_DIR=C:\\embree-4.4.0\\lib\\cmake\\embree-4.4.0
!ENDIF

!IFNDEF TBB_DIR
TBB_DIR=C:\\oneapi-tbb-2021.11.0\\lib\\cmake\\tbb
!ENDIF

!IFNDEF EXTRA_CMAKE_ARGS
EXTRA_CMAKE_ARGS=
!ENDIF

ALL_TARGETS=light

all: $(ALL_TARGETS)

configure:
@if not exist "$(BUILD_DIR)" mkdir "$(BUILD_DIR)"
cmake -S . -B "$(BUILD_DIR)" -G "$(GENERATOR)" -DCMAKE_BUILD_TYPE=$(CONFIG) -Dembree_DIR="$(EMBREE_DIR)" -DTBB_DIR="$(TBB_DIR)" $(EXTRA_CMAKE_ARGS)

light: configure
cmake --build "$(BUILD_DIR)" --target light --config $(CONFIG)

clean:
@if exist "$(BUILD_DIR)" rmdir /s /q "$(BUILD_DIR)"
